config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  get "/health/ready", to: proc { [ 200, {}, [ "ok" ] ] }

  constraints subdomain: "sidekiq" do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest("sidekiq")) &&
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_WEB_PASSWORD"]))
    end if Rails.env.production?
    mount Sidekiq::Web, at: "/"
  end

  constraints subdomain: "admin" do
    resources :sessions, only: %i[show create]
    get "/login" => "sessions#new", as: :login
    delete "/logout" => "sessions#destroy", as: :logout

    resources :email_suppressions, only: :destroy

    get "activity_participations/calendar" => "activity_participations_calendar#show",
      defaults: { format: :ics }
    get "billing/:year" => "billings#show", as: :billing
    get "billing/snapshots/:id" => "billing_snapshots#show", as: :billing_snapshot

    get "settings" => "acps#edit", as: :edit_acp
    get "settings" => "acps#edit", as: :acps
    resource :acp, path: "settings", only: :update

    get "deliveries/next" => "next_delivery#next"
    get "handbook/:id" => "handbook#index", as: :handbook_page

    ActiveAdmin.routes(self)

    namespace :api do
      namespace :v1 do
        resource :configuration, only: :show
        get "basket_contents/current" => "basket_contents#index"
      end
    end
  end

  scope module: "members", as: "members" do
    constraints subdomain: %w[membres mitglieder soci] do
      resources :sessions, only: %i[show create]
      get "/login" => "sessions#new", as: :login
      delete "/logout" => "sessions#destroy", as: :logout

      get "/newsletters/unsubscribe/:token" => "newsletter_subscriptions#destroy", as: "unsubscribe_newsletter"
      #  List-Unsubscribe-Post
      post "/newsletters/unsubscribe/:token/post" => "newsletter_subscriptions#destroy", as: "unsubscribe_newsletter_post"
      post "/newsletters/subscribe/:token" => "newsletter_subscriptions#create", as: "subscribe_newsletter"

      get "/membership", to: redirect("/memberships")
      resources :memberships, only: %i[index edit update]
      resources :baskets, only: %i[edit update]

      scope :membership do
        resource :renewal,
          only: %i[new create],
          as: "membership_renewal",
          controller: "membership_renewals"
        get ":decision" => "membership_renewals#new"
      end

      resources :deliveries, only: :index
      resources :activities, only: :index
      resources :activity_participations, only: %i[index create destroy]
      namespace :shop do
        get "/" => "products#index"
        get "/next" => "products#index", as: :next, next: true
        get "/special/:special_delivery_date" => "products#index", as: :special_delivery
        resources :orders, only: %i[show update destroy] do
          post "confirm", on: :member
          post "unconfirm", on: :member
          resources :order_items, only: %i[create]
        end
      end
      resources :absences, only: %i[index create destroy]
      get "billing" => "billing#index"
      resource :member, only: %i[new show create], path: "" do
        get "welcome", on: :collection
      end
      resource :account, only: %i[show edit update]
      resource :info, only: :show
      resource :contact_sharing, only: %i[show create]
      resource :email_suppression, only: :destroy
    end
  end
end

app/controllers/members/absences_controller.rb
class Members::AbsencesController < Members::BaseController
  include AbsencesHelper

  before_action :ensure_absence_access

  # GET /absences
  def index
    min = Absence.min_started_on
    @absence = Absence.new(
      started_on: min,
      ended_on: (min + 1.day).end_of_week)
  end

  # POST /absences
  def create
    @absence = current_member.absences.new(protected_params)
    @absence.session_id = session_id

    if @absence.save
      flash[:notice] = t(".flash.notice")
      redirect_to members_absences_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  # DELETE /absences/:id
  def destroy
    absence = current_member.absences.find(params[:id])
    absence.destroy

    redirect_to members_absences_path
  end

  private

  def protected_params
    params.require(:absence).permit(:started_on, :ended_on, :note)
  end

  def ensure_absence_access
    redirect_to members_member_path unless display_absence?
  end
end

app/controllers/members/accounts_controller.rb
class Members::AccountsController < Members::BaseController
  # GET /account
  def show
  end

  # GET /account/edit
  def edit
  end

  # PATCH /account
  def update
    if current_member.update(member_params)
      redirect_to members_account_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def member_params
    params
      .require(:member)
      .permit(
        :name,
        :address, :zip, :city, :country_code,
        :emails, :phones, :language,
        :shop_depot_id)
  end
end

app/controllers/members/activities_controller.rb
class Members::ActivitiesController < Members::BaseController
  skip_before_action :authenticate_member!

  # GET /activities.rss
  def index
    @activities = Activity.available
    @limit = params[:limit]&.to_i || 8
    respond_to do |format|
      format.rss
      format.html { redirect_to members_activity_participations_path }
    end
  end
end

app/controllers/members/activity_participations_controller.rb
class Members::ActivityParticipationsController < Members::BaseController
  include ActivitiesHelper

  before_action :ensure_activity_access

  # GET /activity_participations
  def index
    @activities = Activity.available_for(current_member)
    @activity_participation = ActivityParticipation.new(
      activity: @activities.select(&:missing_participants?).first || @activities.first)
    @activity_participation.carpooling_phone ||= current_member.phones_array.first
    @activity_participation.carpooling_city ||= current_member.city
  end

  # POST /activity_participations
  def create
    @activity_participation = current_member.activity_participations.new(protected_params)
    @activity_participation.session_id = session_id

    if @activity_participation.save
      flash[:notice] = t(".flash.notice")
      redirect_to members_activity_participations_path
    else
      @activities = Activity.available_for(current_member)
      unless @activity_participation.carpooling
        @activity_participation.carpooling_phone ||= current_member.phones_array.first
        @activity_participation.carpooling_city ||= current_member.city
      end
      render :index, status: :unprocessable_entity
    end
  end

  # DELETE /activity_participations/:id
  def destroy
    participation = current_member.activity_participations.find(params[:id])
    participation.destroy if participation.destroyable?

    redirect_to members_activity_participations_path
  end

  private

  def protected_params
    params
      .require(:activity_participation)
      .permit(%i[participants_count note carpooling carpooling_phone carpooling_city], activity_ids: [])
  end

  def ensure_activity_access
    redirect_to members_member_path unless display_activity?
  end
end

app/controllers/members/base_controller.rb
class Members::BaseController < ApplicationController
  layout "members"
  before_action :authenticate_member!

  helper_method :current_member

  private

  def authenticate_member!
    if !current_member
      cookies.delete(:session_id)
      redirect_to members_login_path, alert: t("sessions.flash.required")
    elsif current_session&.expired?
      cookies.delete(:session_id)
      redirect_to members_login_path, alert: t("sessions.flash.expired")
    else
      set_sentry_user
      update_last_usage(current_session)
    end
  end

  def current_member
    current_session&.member
  end

  def set_locale
    if params[:locale].in?(Current.acp.languages)
      cookies.permanent[:locale] = params[:locale]
    end
    unless cookies[:locale].in?(Current.acp.languages)
      cookies.delete(:locale)
    end
    I18n.locale =
      current_member&.language ||
      cookies[:locale] ||
      Current.acp.languages.first
  end

  def set_sentry_user
    Sentry.set_user(
      id: "member_#{current_member.id}",
      session_id: current_session.id)
  end

  def current_shop_delivery
    return unless Current.acp.feature?("shop")

    @current_shop_delivery ||=
      Delivery
        .shop_open
        .where(id: coming_delivery_ids)
        .next
  end
  helper_method :current_shop_delivery

  def next_shop_delivery
    return unless Current.acp.feature?("shop")
    return unless current_shop_delivery

    @next_shop_delivery ||=
      Delivery
        .shop_open
        .where.not(id: current_shop_delivery.id)
        .where(id: coming_delivery_ids)
        .next
  end
  helper_method :next_shop_delivery

  def shop_special_deliveries
    return unless Current.acp.feature?("shop")

    @shop_special_deliveries ||= Shop::SpecialDelivery.coming.open.select(&:shop_open?)
  end
  helper_method :shop_special_deliveries

  def coming_delivery_ids
    if depot = current_member.shop_depot
      Delivery
        .coming
        .select { |delivery|
          delivery.shop_open?(depot_id: depot.id, ignore_closing_at: true)
        }
        .map(&:id)
    else
      current_member
        .baskets
        .coming
        .includes(:delivery)
        .select { |basket|
          basket.delivery.shop_open?(depot_id: basket.depot_id, ignore_closing_at: true)
        }
        .map(&:delivery_id)
    end
  end
end

app/controllers/members/baskets_controller.rb
class Members::BasketsController < Members::BaseController
  before_action :load_basket
  before_action :ensure_member_can_update_basket!

  # GET /baskets/:id/edit
  def edit
  end

  # PATCH /baskets/:id
  def update
    @basket.member_update!(basket_params)
    redirect_to members_deliveries_path, notice: t("flash.actions.update.notice")
  end

  private

  def load_basket
    @basket = current_member.baskets.find(params[:id])
  end

  def ensure_member_can_update_basket!
    redirect_to members_deliveries_path unless @basket.can_member_update?
  end

  def basket_params
    permitted =
      params
        .require(:basket)
        .permit(
          :depot_id,
          baskets_basket_complements_attributes: [
            :id, :basket_complement_id, :quantity
          ])
    permitted[:baskets_basket_complements_attributes]&.each { |i, attrs|
      attrs["_destroy"] = true if attrs["quantity"].to_i.zero?
    }
    permitted
  end
end

app/controllers/members/billing_controller.rb
class Members::BillingController < Members::BaseController
  # GET /billing
  def index
    invoices = current_member.invoices.includes(pdf_file_attachment: :blob)
    @membership = current_member.current_or_future_membership
    @open_invoices = invoices.open.order(date: :desc)
    @billing_history = (invoices.history + current_member.payments).sort_by(&:date).reverse
  end
end

app/controllers/members/contact_sharings_controller.rb
class Members::ContactSharingsController < Members::BaseController
  before_action :ensure_contact_sharing_feature
  before_action :ensure_member_next_basket_presence

  # GET /contact_sharing
  def show
    next_basket = current_member.next_basket
    @depot = next_basket.depot
    @members =
      Member
        .sharing_contact
        .where.not(id: current_member.id)
        .joins(:baskets)
        .where(baskets: {
          depot_id: next_basket.depot_id,
          delivery_id: next_basket.delivery_id
        })
        .order(:name)
  end

  # POST /contact_sharing
  def create
    if current_member.update(member_params)
      redirect_to members_contact_sharing_path, notice: t("members.contact_sharings.flash.joined")
    else
      @depot = current_member.next_basket.depot
      render :show, status: :unprocessable_entity
    end
  end

  private

  def ensure_contact_sharing_feature
    redirect_to members_member_path unless Current.acp.feature?("contact_sharing")
  end

  def ensure_member_next_basket_presence
    redirect_to members_member_path unless current_member.next_basket
  end

  def member_params
    params
      .require(:member)
      .permit(:contact_sharing, :terms_of_service)
  end
end

app/controllers/members/deliveries_controller.rb
class Members::DeliveriesController < Members::BaseController
  # GET /deliveries
  def index
    if @next_basket = current_member.next_basket
      membership_ids = [ @next_basket.membership_id ]
      if current_member.future_membership
        membership_ids << current_member.future_membership.id
      end
      @future_baskets =
        Basket
          .where(membership_id: membership_ids)
          .filled
          .coming
          .includes(:delivery, :basket_size, :depot, baskets_basket_complements: :basket_complement)
      @past_baskets =
        @next_basket
          .membership
          .baskets
          .filled
          .past
          .includes(:delivery, :basket_size, :depot, baskets_basket_complements: :basket_complement)
    else
      redirect_to members_login_path
    end
  end
end

app/controllers/members/email_suppressions_controller.rb
class Members::EmailSuppressionsController < Members::BaseController
  before_action :ensure_non_admin_originated_session!

  # DELETE /email_suppression
  def destroy
    email = current_session.email
    EmailSuppression.unsuppress!(email, stream_id: "broadcast")

    redirect_to members_account_path, notice: t(".flash.notice")
  end

  private

  def ensure_non_admin_originated_session!
    if current_session.admin_originated?
      redirect_to members_account_path
    end
  end
end

app/controllers/members/halfdays_controller.rb
class Members::HalfdaysController < Members::BaseController
  skip_before_action :authenticate_member!

  # GET /halfdays.rss
  def index
    @halfdays = Halfday.available
    @limit = params[:limit]&.to_i || 8
    respond_to do |format|
      format.rss
    end
  end
end

app/controllers/members/infos_controller.rb
class Members::InfosController < Members::BaseController
  before_action :ensure_info_presence

  # GET /info
  def show
  end

  private

  def ensure_info_presence
    unless Current.acp.member_information_text?
      redirect_to members_member_path
    end
  end
end

app/controllers/members/membership_renewals_controller.rb
class Members::MembershipRenewalsController < Members::BaseController
  before_action :redirect_renewal_decision_params!, only: :new

  # GET /membership/renewal/new
  # GET /membership/:decision
  def new
    @membership = current_member.current_year_membership.dup
    @membership.renewal_decision = params[:decision]
    set_basket_complements

    redirect_to members_member_path unless @membership&.renewal_opened?
  end

  # POST /membership/renewal
  def create
    membership = current_member.current_year_membership
    case params.require(:membership).require(:renewal_decision)
    when "cancel"
      membership.cancel!(renewal_params)
      flash[:notice] = t(".flash.canceled")
    when "renew"
      membership.renew!(renewal_params)
      flash[:notice] = t(".flash.renewed")
    end

    redirect_to members_memberships_path
  rescue => e
    Sentry.capture_exception(e, extra: {
      member_id: current_member.id,
      membership_id: membership&.id
    })
    redirect_back fallback_location: members_memberships_path, alert: t(".flash.error")
  end

  private

  def set_basket_complements
    complement_ids =
      BasketComplement
        .visible
        .member_ordered
        .select { |bc| bc.deliveries_count.positive? }
        .map(&:id)
    complement_ids.each do |id|
      quantity =
        current_member
          .current_year_membership
          .memberships_basket_complements
          .find { |mbc| mbc.basket_complement_id == id }
          &.quantity
      @membership.memberships_basket_complements.build(
        quantity: quantity || 0,
        basket_complement_id: id)
    end
  end

  def redirect_renewal_decision_params!
    if decision = params.dig(:membership, :renewal_decision)
      redirect_to url_for(decision: decision)
    end
  end

  def renewal_params
    permitted = params
      .require(:membership)
      .permit(*%i[
        renewal_annual_fee
        renewal_note
        basket_size_id
        basket_price_extra
        activity_participations_demanded_annually
        depot_id
        delivery_cycle_id
        billing_year_division
      ], memberships_basket_complements_attributes: [
        :basket_complement_id, :quantity
      ])
      permitted[:memberships_basket_complements_attributes]&.select! { |i, attrs|
        attrs["quantity"].to_i > 0
      }
      permitted
  end
end

app/controllers/members/newsletter_subscriptions_controller.rb
require "bcrypt"

class Members::NewsletterSubscriptionsController < Members::BaseController
  layout "members"
  skip_before_action :authenticate_member!
  before_action :ensure_valid_token

  # POST /newsletters/subscribe/:token
  def create
    EmailSuppression.unsuppress!(email,
      stream_id: "broadcast",
      origin: "Customer")
  end

  # GET /newsletters/unsubscribe/:token
  def destroy
    EmailSuppression.suppress!(email,
      stream_id: "broadcast",
      reason: "ManualSuppression",
      origin: "Customer")
  end

  private

  def email
    @email ||= Newsletter::Audience.decrypt_email(params[:token])
  end
  helper_method :email

  def member
    @member ||= Member.find_by_email(email)
  end

  def current_member; nil end

  def ensure_valid_token
    unless member
      render :invalid, status: :not_found
    end
  end
end

app/views/members/memberships/_membership.html.slim
h2 class="mt-8 text-lg font-bold text-gray-900 dark:text-gray-100"
  = membership.fiscal_year

  - if membership.can_member_update?
    = link_to edit_members_membership_path(membership), title: t('.edit'), class: 'ml-1.5 p-2 text-gray-400 dark:text-gray-600 hover:text-green-500' do
      = inline_svg_tag 'members/pencil_square.svg', class: 'mb-1.5 inline h-5 w-5 fill-stroke'

ul class='my-2 md:mr-4 -mx-2 relative p-2 space-y-2' id=membership.fiscal_year.year
  li class='flex flex-row items-center'
    = inline_svg_tag 'members/calendar.svg', class: 'h-6 w-6 flex-shrink-0 fill-stroke text-gray-300 dark:text-gray-700'
    span class='ml-2'
      = [membership.started_on, membership.ended_on].map { |d| l(d) }.join(' – ')

  li class='mt-1 flex flex-row items-center'
    = inline_svg_tag 'members/basket.svg', class: 'h-6 w-6 flex-shrink-0 fill-stroke text-gray-300 dark:text-gray-700'
    span class='ml-2 flex flex-col'
      span = basket_size_description(membership)
      - complements = membership.memberships_basket_complements.includes(:basket_complement)
      - if complements.any?
        span = basket_complements_description(complements)

  li class='mt-1 flex flex-row items-center'
    = inline_svg_tag 'members/map.svg', class: 'h-6 w-6 flex-shrink-0 fill-stroke text-gray-300 dark:text-gray-700'
    span class='ml-2'
      - depot = membership.depot
      - if depot.full_address
        = link_to "https://www.google.com/maps?q=#{depot.full_address}", title: depot.full_address, target: :blank, class: 'hover:text-green-500' do
          = h depot.public_name
      - else
        = h depot.public_name

  li class='mt-1 flex flex-row items-center'
    = inline_svg_tag 'members/truck.svg', class: 'h-6 w-6 flex-shrink-0 fill-stroke text-gray-300 dark:text-gray-700'
    span class='ml-2'
      = link_to members_deliveries_path do
        = "#{membership.baskets_count} #{Delivery.model_name.human(count: membership.baskets_count)}"
        - if membership.trial?
          = ", #{t('.remaning_trial_baskets_count', count: membership.remaning_trial_baskets_count)}"
      - if Current.acp.feature?('absence') && membership.baskets.absent.any?
        = ', '
        = link_to members_absences_path do
          = t('.absent_baskets_count', count: membership.baskets.absent.count)

  - if Current.acp.feature?('activity')
    li class='mt-1 flex flex-row items-center'
      = inline_svg_tag 'members/hand.svg', class: 'h-6 w-6 flex-shrink-0 fill-stroke text-gray-300 dark:text-gray-700'
      span class='ml-2'
        = "#{activities_human_name}: "
        = link_to members_activity_participations_path do
          = t('.activity_participations_demanded', count: membership.activity_participations_demanded)

  li
    li class='mt-1 flex flex-row items-center'
      = inline_svg_tag 'members/cash.svg', class: 'h-6 w-6 flex-shrink-0 fill-stroke text-gray-300 dark:text-gray-700'
      span class='ml-2'
        - if current_member.salary_basket?
          span class="italic text-gray-400 dark:text-gray-600"
            = t('.price_salary_basket')
        - else
          span class="flex flex-row items-center"
            = link_to members_billing_path do
              = cur(membership.price)
            - if membership.invoices.any?
              span class='m-0 flex items-center tooltip-toggle' onclick="" data-tooltip="#{t('.price_tooltip')}"
                = inline_svg_tag 'members/info_circle.svg', class: 'ml-2 stroke-2'

app/views/members/memberships/edit.html.slim
h1 class="mt-1 mb-8 text-xl sm:text-2xl font-extrabold text-gray-900 dark:text-gray-100"
  = t('.title', year: @membership.fiscal_year)

h2 class="mt-8 text-lg font-bold text-gray-900 dark:text-gray-100"
  = t('.subtitle')

- if Current.acp.membership_update_text?
  div class='trix mt-2 mb-8 justify'
    = Current.acp.membership_update_text

section class="mt-4 w-full"
  = simple_form_for @membership do |f|
    - member_updatable_baskets = @membership.member_updatable_baskets

    - if Current.acp.membership_depot_update_allowed?
      div class='space-y-8'
        = f.input :depot_id, as: :radio_buttons, collection: depots_collection(membership: @membership, delivery_cycle: @membership.delivery_cycle, only_price_per_delivery: true), label: Depot.model_name.human, required: true, input_html: { class: 'mr-4 flex-none h-6 w-6 border-2 border-gray-300 dark:border-gray-700 text-green-500 dark:bg-black focus:outline-none focus:ring-green-500 focus:border-green-500 cursor-pointer' }, item_label_class: 'border-gray-200 dark:border-gray-800 border rounded px-4 py-2 flex flex-row flex-nowrap items-center cursor-pointer', wrapper_class: 'flex flex-col space-y-2', label_html: { class: 'text-sm font-medium text-gray-700 dark:text-gray-300' }

    div class="mt-16"
      p class="mt-8 italic text-justify md:text-right text-sm text-gray-500 dark:text-gray-400"
        = t('.updateable_baskets', count: member_updatable_baskets.size, first_date: l(member_updatable_baskets.first.delivery.date))

    div class='flex flex-col md:flex-row justify-end mt-4 md:space-x-4'
      = link_to t('.cancel_link'), members_memberships_path, class: 'button order-2 md:order-1 mt-4 md:mt-0 md:min-w-min min-w-full text-center py-2 px-4 border border-green-400 dark:border-green-600 hover:border-green-500 hover:bg-green-500 font-medium rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 text-base cursor-pointer'
      = f.button :submit, t('.submit'), class: 'order-1 md:order-2 min-w-full md:min-w-min py-2 px-6 border border-green-400 dark:border-green-600 bg-green-400 dark:bg-green-600 hover:border-green-500 hover:bg-green-500 text-white font-medium rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 text-base cursor-pointer'

app/views/members/memberships/index.html.slim
h1 class="mt-1 mb-8 text-xl sm:text-2xl font-extrabold text-gray-900 dark:text-gray-100"
  = Membership.model_name.human

= render @membership

- if @membership.renewal_opened?
  #renewal class='focus:outline-none'
    h2 class="mt-8 text-lg font-bold text-gray-900 dark:text-gray-100"
      = t('.renewal.title')

    div class='trix mt-2 justify'
      = Current.acp.open_renewal_text
    = simple_form_for @membership, url: new_members_membership_renewal_path, method: :get, data: { remote: false } do |f|
      div class='mt-6'
        = f.input :renewal_decision, as: :radio_buttons, collection: renewal_decisions_collection, required: false, label: t('.renewal.options_label'), label_html: { class: 'text-sm font-medium text-gray-700 dark:text-gray-300' }, input_html: { class: 'mr-4 flex-none h-6 w-6 border-2 border-gray-300 dark:border-gray-700 text-green-500 dark:bg-black focus:outline-none focus:ring-green-500 focus:border-green-500 cursor-pointer' }, item_label_class: 'border-gray-200 dark:border-gray-800 border rounded px-4 py-2 flex flex-row flex-nowrap items-center cursor-pointer', wrapper_class: 'flex flex-col space-y-2'

      div class='mt-2 text-right'
        = f.submit t('.renewal.submit'), class: 'min-w-full md:min-w-min py-2 px-6 border border-green-400 dark:border-green-600 bg-green-400 dark:bg-green-600 hover:border-green-500 hover:bg-green-500 text-white font-medium rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 text-base cursor-pointer'

- elsif @membership.renewed?
  = render @membership.renewed_membership

- elsif @membership.canceled? && @membership.current?
  p class='mt-8 justify italic'
    = t('.renewal.canceled', last_delivery_date: l(@membership.deliveries.last.date)).html_safe

app/views/members/memberships/show.html.slim
h1 class="mt-1 mb-8 text-xl sm:text-2xl font-extrabold text-gray-900 dark:text-gray-100"
  = Membership.model_name.human

= render @membership

- if @membership.renewal_opened?
  #renewal class='focus:outline-none'
    h2 class="mt-8 text-lg font-bold text-gray-900 dark:text-gray-100"
      = t('.renewal.title')

    div class='trix mt-2 justify'
      = Current.acp.open_renewal_text
    = simple_form_for @membership, url: new_members_membership_renewal_path, method: :get, data: { remote: false } do |f|
      div class='mt-6'
        = f.input :renewal_decision, as: :radio_buttons, collection: renewal_decisions_collection, required: false, label: t('.renewal.options_label'), label_html: { class: 'text-sm font-medium text-gray-700 dark:text-gray-300' }, input_html: { class: 'mr-4 flex-none h-6 w-6 border-2 border-gray-300 dark:border-gray-700 text-green-500 dark:bg-black focus:outline-none focus:ring-green-500 focus:border-green-500 cursor-pointer' }, item_label_class: 'border-gray-200 dark:border-gray-800 border rounded px-4 py-2 flex flex-row flex-nowrap items-center cursor-pointer', wrapper_class: 'flex flex-col space-y-2'

      div class='mt-2 text-right'
        = f.submit t('.renewal.submit'), class: 'min-w-full md:min-w-min py-2 px-6 border border-green-400 dark:border-green-600 bg-green-400 dark:bg-green-600 hover:border-green-500 hover:bg-green-500 text-white font-medium rounded-md focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 text-base cursor-pointer'

- elsif @membership.renewed?
  = render @membership.renewed_membership

- elsif @membership.canceled? && @membership.current?
  p class='mt-8 justify italic'
    = t('.renewal.canceled', last_delivery_date: l(@membership.deliveries.last.date)).html_safe