config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  get "/health/ready", to: proc { [ 200, {}, [ "ok" ] ] }

  constraints subdomain: "sidekiq" do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest("sidekiq")) &&
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_WEB_PASSWORD"]))
    end if Rails.env.production?
    mount Sidekiq::Web, at: "/"
  end

  constraints subdomain: "admin" do
    resources :sessions, only: %i[show create]
    get "/login" => "sessions#new", as: :login
    delete "/logout" => "sessions#destroy", as: :logout

    resources :email_suppressions, only: :destroy

    get "activity_participations/calendar" => "activity_participations_calendar#show",
      defaults: { format: :ics }
    get "billing/:year" => "billings#show", as: :billing
    get "billing/snapshots/:id" => "billing_snapshots#show", as: :billing_snapshot

    get "settings" => "acps#edit", as: :edit_acp
    get "settings" => "acps#edit", as: :acps
    resource :acp, path: "settings", only: :update

    get "deliveries/next" => "next_delivery#next"
    get "handbook/:id" => "handbook#index", as: :handbook_page

    ActiveAdmin.routes(self)

    namespace :api do
      namespace :v1 do
        resource :configuration, only: :show
        get "basket_contents/current" => "basket_contents#index"
      end
    end
  end

  scope module: "members", as: "members" do
    constraints subdomain: %w[membres mitglieder soci] do
      resources :sessions, only: %i[show create]
      get "/login" => "sessions#new", as: :login
      delete "/logout" => "sessions#destroy", as: :logout

      get "/newsletters/unsubscribe/:token" => "newsletter_subscriptions#destroy", as: "unsubscribe_newsletter"
      #  List-Unsubscribe-Post
      post "/newsletters/unsubscribe/:token/post" => "newsletter_subscriptions#destroy", as: "unsubscribe_newsletter_post"
      post "/newsletters/subscribe/:token" => "newsletter_subscriptions#create", as: "subscribe_newsletter"

      get "/membership", to: redirect("/memberships")
      resources :memberships, only: %i[index edit update]
      resources :baskets, only: %i[edit update]

      scope :membership do
        resource :renewal,
          only: %i[new create],
          as: "membership_renewal",
          controller: "membership_renewals"
        get ":decision" => "membership_renewals#new"
      end

      resources :deliveries, only: :index
      resources :activities, only: :index
      resources :activity_participations, only: %i[index create destroy]
      namespace :shop do
        get "/" => "products#index"
        get "/next" => "products#index", as: :next, next: true
        get "/special/:special_delivery_date" => "products#index", as: :special_delivery
        resources :orders, only: %i[show update destroy] do
          post "confirm", on: :member
          post "unconfirm", on: :member
          resources :order_items, only: %i[create]
        end
      end
      resources :absences, only: %i[index create destroy]
      get "billing" => "billing#index"
      resource :member, only: %i[new show create], path: "" do
        get "welcome", on: :collection
      end
      resource :account, only: %i[show edit update]
      resource :info, only: :show
      resource :contact_sharing, only: %i[show create]
      resource :email_suppression, only: :destroy
    end
  end
end

app/models/basket_content/product.rb
class BasketContent
  class Product < ApplicationRecord
    include TranslatedAttributes

    translated_attributes :name, required: true

    has_many :basket_contents
    has_many :deliveries, through: :basket_contents

    with_options class_name: "BasketContent" do
      has_one :latest_basket_content, -> {
        joins(:delivery).merge(Delivery.unscoped.order(date: :desc))
      }
      has_one :latest_basket_content_in_kg, -> {
        joins(:delivery).merge(Delivery.unscoped.order(date: :desc)).in_kg
      }
      has_one :latest_basket_content_in_pc, -> {
        joins(:delivery).merge(Delivery.unscoped.order(date: :desc)).in_pc
      }
    end

    default_scope { order_by_name }

    validates :names, uniqueness: true

    def url_domain
      return unless url?

      uri = URI.parse(url)
      PublicSuffix.parse(uri.host).to_s
    end

    def can_destroy?
      basket_contents.none?
    end
  end
end

app/models/shop/delivery_total.rb
module Shop
  class DeliveryTotal
    include ActiveModel::Model
    attr_accessor :product, :product_variant, :quantity, :amount

    def self.all_by_producer(delivery)
      order_items = Order
        .where(delivery: delivery)
        .all_without_cart
        .eager_load(items: [ :product_variant, product: :producer ])
        .order(Arel.sql("shop_producers.name, shop_products.names->>'#{I18n.locale}', shop_product_variants.names->>'#{I18n.locale}'"))
        .flat_map(&:items)
        .group_by { |i| i.product.producer }

      order_items.map { |producer, items|
        all = items.group_by { |i|
          [ i.product, i.product_variant ]
        }.map { |(product, product_variant), items|
          new(
            product: product,
            product_variant: product_variant,
            quantity: items.sum(&:quantity),
            amount: items.sum(&:amount))
        }
        all << new(amount: items.sum(&:amount))
        [ producer, all ]
      }
    end
  end
end

app/models/shop/null_producer.rb
module Shop
  class NullProducer
    include ActiveModel::Model
    include Singleton

    def id; "null" end

    def name
      I18n.t("shop.producers.null_producer")
    end

    def website_url?
      false
    end
  end
end

app/models/shop/producer.rb
module Shop
  class Producer < ApplicationRecord
    self.table_name = "shop_producers"

    include TranslatedRichTexts
    include Discardable

    default_scope { order(:name) }

    translated_rich_texts :description

    has_many :products, class_name: "Shop::Product"

    validates :name, presence: true
    validates :website_url, format: {
      with: %r{\Ahttps?://.*\z},
      allow_blank: true
    }

    def self.find(*args)
      return NullProducer.instance if args.first == "null"

      super
    end

    def can_update?; true end

    def can_discard?
      products.any?(&:discarded?) && products.none?(&:kept?)
    end

    def can_delete?
      products.none?
    end
  end
end

app/models/shop/product_variant.rb
module Shop
  class ProductVariant < ApplicationRecord
    self.table_name = "shop_product_variants"

    include TranslatedAttributes
    include Discardable

    translated_attributes :name, required: true

    default_scope { order(:price).order_by_name }

    belongs_to :product, class_name: "Shop::Product", optional: true
    has_many :order_items, class_name: "Shop::OrderItem", inverse_of: :product_variant
    has_many :orders, through: :order_items
    has_many :uninvoiced_orders, -> { uninvoiced }, through: :order_items, source: :order

    scope :available, -> { where(available: true) }
    scope :unavailable, -> { where(available: false) }

    validates :available, inclusion: [ true, false ]
    validates :price,
      presence: true,
      numericality: { greater_than_or_equal_to: 0 }
    validates :stock,
      numericality: { greater_than_or_equal_to: 0, allow_nil: true }
    validates :weight_in_kg,
      numericality: { greater_than: 0, allow_nil: true }

    def unavailable?
      !available?
    end

    def out_of_stock?
      stock&.zero?
    end

    def available_stock?(quantity = 1)
      return true if stock.nil?

      stock >= quantity
    end

    def decrement_stock!(by)
      return if stock.nil?

      decrement! :stock, by
    end

    def increment_stock!(by)
      return if stock.nil?

      increment! :stock, by
    end

    def can_discard?
      uninvoiced_orders.none?
    end

    def can_delete?
      order_items.none?
    end
  end
end

app/controllers/members/shop/base_controller.rb
class Members::Shop::BaseController < Members::BaseController
  before_action :ensure_shop_feature
  before_action :ensure_delivery

  private

  def ensure_shop_feature
    redirect_to members_member_path unless Current.acp.feature?("shop")
  end

  def ensure_delivery
    unless delivery
      redirect_to members_member_path
    end
  end

  def shop_path
    case @order&.delivery
    when next_shop_delivery; members_shop_next_path
    when Shop::SpecialDelivery; members_shop_special_delivery_path(@order.delivery.date)
    else members_shop_path
    end
  end
  helper_method :shop_path

  def available_products
    @available_products ||= all_available_products
  end
  helper_method :available_products

  def available_producers
    @available_producers ||=
      all_available_products(params.slice(:tag_id))
        .map(&:producer)
        .compact
        .uniq
        .sort_by(&:name) - [ Shop::NullProducer.instance ]
  end
  helper_method :available_producers

  def available_tags
    @available_tags ||=
      all_available_products(params.slice(:producer_id))
        .flat_map(&:tags)
        .uniq
        .sort_by(&:name)
  end
  helper_method :available_tags

  def all_available_products(pparams = params)
    products = delivery.available_shop_products(current_member.next_basket&.depot)
    products = products.preload(:variants, :tags, :producer, "rich_text_description_#{I18n.locale}".to_sym)
    if pparams[:producer_id].present?
      products = products.where(producer_id: pparams[:producer_id])
    end
    if pparams[:tag_id].present?
      products =
        products
          .joins(:shop_products_tags)
          .where(shop_products_tags: { tag_id: pparams[:tag_id] })
    end
    products
  end
end

app/controllers/members/shop/order_items_controller.rb
class Members::Shop::OrderItemsController < Members::Shop::BaseController
  before_action :find_order

  # POST /shop/orders/:order_id/order_items
  def create
    @item = @order.items.find_or_initialize_by(product_variant_id: product_variant_id) do |i|
      i.quantity = 0
    end
    @item.quantity += 1
    params.permit!

    respond_to do |format|
      if @item.save
        @order.reload
        format.html { redirect_to shop_path }
        format.turbo_stream
      else
        format.html { render "members/shop/products/index", status: :unprocessable_entity }
      end
    end
  end

  private

  def find_order
    @order ||=
      Shop::Order
      .where(delivery: [ current_shop_delivery, next_shop_delivery, *shop_special_deliveries ].compact)
      .where(member_id: current_member.id)
        .includes(items: [ :product, :product_variant ])
        .find(params[:order_id])
  end

  def delivery
    find_order&.delivery
  end
  helper_method :delivery

  def product_variant_id
    params.require(:variant_id)
  end
end

app/controllers/members/shop/orders_controller.rb
class Members::Shop::OrdersController < Members::Shop::BaseController
  before_action :find_order
  before_action :ensure_order_not_empty
  before_action :ensure_order_state

  # GET /shop/orders/:id
  def show
    respond_to do |format|
      format.html { render :show }
      format.turbo_stream
    end
  end

  # PUT/PATCH /shop/orders/:id
  def update
    respond_to do |format|
      if @order.update(order_params)
        if @order.items.empty?
          format.html { redirect_to shop_path }
          format.turbo_stream { redirect_to shop_path }
        else
          format.html { redirect_to members_shop_order_path(@order) }
          format.turbo_stream
        end
      else
        format.html { render :show, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  # POST /shop/orders/:id/confirm
  def confirm
    @order.confirm!
    redirect_to members_shop_order_path(@order), notice: t(".notice")
  rescue InvalidTransitionError, ActiveRecord::RecordInvalid
    render :show, status: :unprocessable_entity
  end

  # POST /shop/orders/:id/unconfirm
  def unconfirm
    @order.unconfirm!
    redirect_to members_shop_order_path(@order)
  rescue InvalidTransitionError
    render :show, status: :unprocessable_entity
  end

  # DELETE /shop/orders/:id
  def destroy
    @order.destroy
    redirect_to shop_path
  end

  private

  def find_order
    @order ||=
      Shop::Order
        .where(delivery: [ current_shop_delivery, next_shop_delivery, *shop_special_deliveries ].compact)
        .where(member_id: current_member.id)
        .includes(items: [ :product, :product_variant ])
        .find(params[:id])
  end

  def delivery
    find_order&.delivery
  end
  helper_method :delivery

  def ensure_order_not_empty
    if @order.items.empty?
      redirect_to shop_path, status: :see_other
    end
  end

  def ensure_order_state
    if @order.cart? && !@order.shop_open?
      redirect_to shop_path, status: :see_other
    end
  end

  def order_params
    params
      .require(:shop_order)
      .permit(:amount_percentage, items_attributes: %i[id quantity])
      .tap do |whitelisted|
        unless whitelisted[:amount_percentage].to_i.in?(Current.acp[:shop_member_percentages])
          whitelisted[:amount_percentage] = nil
        end
        whitelisted[:items_attributes].each do |_, item|
          if item[:quantity] == "0"
            item.delete(:quantity)
            item[:_destroy] = true
          end
        end
      end
  end
end

app/controllers/members/shop/products_controller.rb
class Members::Shop::ProductsController < Members::Shop::BaseController
  before_action :ensure_next_shop_delivery!
  before_action :find_or_create_order!
  before_action :ensure_order_cart_state!

  # GET /shop
  def index
    params.permit!
  end

  private

  def find_or_create_order!
    @order =
      delivery
        .shop_orders
        .includes(items: [ :product, :product_variant ])
        .find_or_create_by!(member_id: current_member.id)
  end

  def delivery
    if params[:next]
      next_shop_delivery
    elsif params[:special_delivery_date]
      shop_special_deliveries.detect { |d| d.date.to_s == params[:special_delivery_date] }
    else
      current_shop_delivery
    end
  end
  helper_method :delivery

  def ensure_order_cart_state!
    unless @order.cart?
      redirect_to members_shop_order_path(@order)
    end
  end

  def ensure_next_shop_delivery!
    if params[:next] && (current_shop_delivery.shop_open? || !next_shop_delivery)
      redirect_to members_shop_path
    end
  end
end

app/helpers/shop_helper.rb
module ShopHelper
  def show_shop_menu?
    return unless Current.acp.feature?("shop")
    return unless current_shop_delivery || shop_special_deliveries.any?

    !Current.acp.shop_admin_only || current_session.admin_originated?
  end

  def live_stock(variant, order)
    return unless variant.stock

    variant_order = order.items.find { |i| i.product_variant_id == variant.id }

    stock = variant.stock
    stock -= variant_order.quantity if variant_order
    stock
  end

  def display_variants(arbre, product)
    arbre.ul do
      product.variants.each do |variant|
        arbre.li class: ("unavailable" unless variant.available?) do
          arbre.span do
            link_to edit_shop_product_path(product, anchor: :variants) do
              parts = [ variant.name ]
              parts << cur(variant.price)
              parts << "<b>#{variant.stock}x</b>" unless variant.stock.nil?
              parts.join(", ").html_safe
            end
          end
        end
      end
    end
  end

  def products_collection
    Shop::Product.kept.includes(:variants).order_by_name.map do |product|
      [ product.name, product.id, disabled: product.variants.all?(&:out_of_stock?) ]
    end
  end

  def shop_member_percentages_collection
    options = Current.acp[:shop_member_percentages].reverse.map do |percentage|
      text =
        if percentage.positive?
          t("shop.percentage.positive", percentage: percentage)
        else
          t("shop.percentage.negative", percentage: percentage)
        end
      [ text, percentage ]
    end
  end

  def shop_member_percentages_label(order)
    if order.amount_percentage.in?(Current.acp[:shop_member_percentages])
      return t("shop.percentages_title.remove")
    end

    if Current.acp[:shop_member_percentages].all?(&:positive?)
      t("shop.percentages_title.positive")
    elsif Current.acp[:shop_member_percentages].all?(&:negative?)
      t("shop.percentages_title.negative")
    else
      t("shop.percentages_title.mixed")
    end
  end

  def shop_deliveries_collection
    (Delivery.shop_open + Shop::SpecialDelivery.all).sort_by(&:date).map do |delivery|
      [ delivery.display_name, delivery.to_global_id ]
    end
  end

  def product_variants_collection(product_id)
    Shop::Product.all.includes(:variants).order_by_name.flat_map do |product|
      product.variants.map do |variant|
        [
          variant.name,
          variant.id,
          data: { product_id: variant.product_id, disabled: !!variant.out_of_stock? },
          disabled: (variant.out_of_stock? || product.id != product_id)
        ]
      end
    end
  end

  def delivery_title(delivery)
    title =
      case delivery
      when Delivery; Delivery.model_name.human
      when Shop::SpecialDelivery; delivery.title
      end
    t("members.shop.products.index.delivery_title",
      title: title,
      date: l(@order.delivery.date, format: :long))
  end
end

app/views/members/shop/products/_product.html.slim
div class=''
  h3 class="font-medium flex flex-row items-center text-gray-800 dark:text-gray-200"
    span
      = product.name
    - if product.tags.any?
      ul class='ml-2 flex items-center space-x-2'
        - product.tags.each do |tag|
          li = render partial: 'members/shop/products/tag', object: tag

  - if params[:producer_id].blank? && product.producer_id?
    div class='mt-1 text-sm font-medium'
      span class='flex flex-row items-center'
        = link_to params.merge(producer_id: product.producer_id) do
          = product.producer.name
        - if product.producer.website_url?
          = link_to product.producer.website_url, target: :blank, class: "ml-1 flex flex-row items-center" do
            = inline_svg_tag 'members/link.svg'

  - if product.description?
    div class='mt-2 text-sm'
      == product.description

  ul class="mt-2 divide-y dark:divide-gray-700"
    - product.variants.select(&:available?).each do |variant|
      li class="-ml-1 p-1 w-full hover:bg-gray-100 dark:hover:bg-gray-900"
        = turbo_frame_tag "product_variant_#{variant.id}" do
          = render partial: 'members/shop/products/variant', object: variant

app/views/members/shop/products/_tag.html.slim
- if params[:tag_id] == tag.id.to_s
  = link_to params.merge(tag_id: nil) do
    span class='flex items-center border border-green-400 hover:border-green-500 dark:border-green-600 py-1 px-2 rounded-full text-gray-600 dark:text-gray-300 hover:text-white text-xs bg-green-400 dark:bg-green-600 hover:bg-green-500'
      = tag.emoji
      span class='ml-1'
        = tag.name
- else
  = link_to params.merge(tag_id: tag.id) do
    span class='flex items-center dark:text-gray-400 border dark:border-gray-700 py-1 px-2 rounded-full text-gray-500 hover:text-white text-xs bg-gray-100 dark:bg-gray-700 hover:bg-green-500 hover:border-green-500'
      = tag.emoji
      span class='ml-1'
        = tag.name

app/views/members/shop/products/_variant.html.slim
- live_stock = live_stock(variant, @order)
div class="flex flex-row items-center #{'text-gray-300' if live_stock&.zero? }"
  div class="flex-grow flex items-center mr-2"
    span
      = variant.name
    - case live_stock
    - when 1..5
      span class="ml-2 px-2 text-xs text-red-500 dark:text-red-400 rounded-full bg-red-100 dark:bg-red-800 whitespace-nowrap"
        = t('.live_stock', count: live_stock)
    - when ..0
      span class="ml-2 px-2 text-xs text-gray-400 dark:text-gray-500 rounded-full bg-gray-200 dark:bg-gray-800 whitespace-nowrap"
        = t('.live_stock', count: 0)

  div class="ml-2 flex-none"
    = cur(variant.price)

  div class="ml-2 flex-none"
    - if !live_stock || live_stock.positive?
      = button_to members_shop_order_order_items_path(@order), method: :post, title: t('.add_to_basket'), class: 'bg-gray-200 dark:bg-gray-800 hover:bg-green-500 font-medium rounded-md focus:outline-none focus:ring-green-500 focus:z-10 text-sm cursor-pointer flex items-center', disabled: live_stock&.zero?, params: { variant_id: variant.id } do
        = inline_svg_tag 'members/shopping_cart.svg', class: 'p-1 h-6 w-10 fill-stroke hover:text-white'
    - else
      span class='text-gray-300 dark:text-gray-700 bg-gray-200 dark:bg-gray-800 rounded-md cursor-not-allowed flex items-center'
        = inline_svg_tag 'members/shopping_cart.svg', class: 'p-1 h-6 w-10 fill-stroke'

app/views/members/shop/products/index.html.slim
= render partial: 'members/shop/shared/header'

- if @order.shop_open?
  p class="mt-2"
    = t('.closing_at_html', date: l(@order.delivery.shop_closing_at, format: :long))

  div class="mt-6 h-12 w-full"
    div data-controller='sticky' data-sticky-target='container' data-sticky-offset-value="114" data-sticky-desktop-offset-value="178" data-sticky-sticky-class="fixed top-4 md:-ml-10 inset-x-4 md:inset-x-1/2" data-action='scroll@window->sticky#update resize@window->sticky#update'
      div class="-mx-4 md:-mx-0 px-4 md:px-0 bg-white md:bg-transparent"
        div class="shadow-md mx-0 md:mx-auto w-full md:w-96 flex flex-col border dark:border-gray-700 rounded bg-gray-100 dark:bg-gray-900 text-gray-400 dark:text-gray-600"
          = turbo_frame_tag 'cart' do
            = render partial: 'members/shop/orders/cart'

  h2 class="mt-8 text-lg font-bold text-gray-900 dark:text-gray-100"
    = t('.available_product')

  - if available_producers.any?
    div class='mt-2' data-controller='form-submitter'
      = form_tag shop_path, method: :get, data: { form_submitter_target: 'form' } do
        - if params[:tag_id].present?
          = hidden_field_tag :tag_id, params[:tag_id]
        = select_tag :producer_id, options_from_collection_for_select(available_producers, :id, :name, params[:producer_id]), include_blank: t('.all_producers'), class: "mt-1 dark:bg-black w-full md:w-auto text-sm px-3 md:pl-3 md:pr-16 py-1 border rounded-full focus:outline-none focus:ring-green-500 focus:border-green-500 focus:z-10 #{params[:producer_id].present? ? 'text-gray-600 bg-green-400 dark:bg-green-600 dark:text-gray-300 border-green-400 dark:border-green-600' : 'text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-800 border-gray-200 dark:border-gray-700'}", data: { action: "form-submitter#submit" }

  - if available_tags.any?
    ul class='mt-2 flex items-center space-x-2'
      - available_tags.each do |tag|
        li = render partial: 'members/shop/products/tag', object: tag

  - if params[:producer_id].present?
    - producer = Shop::Producer.find(params[:producer_id])
    div class='mt-2 text-sm border dark:border-gray-700 rounded p-4 space-y-2'
      - if producer.description?
        div
          == h producer.description
      - if producer.website_url?
        = link_to producer.website_url, producer.website_url, target: :blank, class: "text-sm flex flex-row items-center"

  div class='mt-8 space-y-8'
    = render partial: 'members/shop/products/product', collection: available_products

- else
  p class="mt-2"
    = t('.closed_at_html', date: l(@order.delivery.shop_closing_at, format: :long))

  - if next_shop_delivery
    div class='mt-12 flex flex-row justify-center'
      = link_to members_shop_next_path, class: 'cursor-pointer underline' do
        div class='flex flex-row items-center'
          = inline_svg_tag('members/shopping_cart.svg', class: 'w-5 h-5 stroke-current')
          span class='ml-1 text-base font-normal'
            = t('.next_shop_delivery_link', date: l(next_shop_delivery.date))

- if Current.acp.shop_terms_of_sale_url
  div class='mt-24 text-sm text-gray-400 dark:text-gray-600 text-center underline'
    = link_to t('members.shop.terms_of_sale'), Current.acp.shop_terms_of_sale_url, target: '_blank'